# --------------CONFIG FILE-----------------------


CONFIG:
  #------GPU setting -------------------------------
  for_debug: False
  train_gpu: [0]
  test_gpu: [4]

  # ------------random seed -------------------------
  manual_seed: 123
  sync_bn: False

  # ------------dataset setting----------------------
  data_name: 's3dis'
  classes: 13             # 13 cateogries for S3DIS (13 labeled)
  data_root: "/data1/fz20/dataset/sp_s3dis_dataset"
  names_path: "/data1/fz20/project/point-transformer-boundary/data/s3dis/s3dis_names.txt"
  save_path: runs/s3dis

  num_point: 8999        # actually 14999+1=15000
  # very important!!!!
  # rate: 0.008             # 0.008 for training and 0.0069 for testing
  rate: 0.0069
  add_rate: 0.002       # 用于IA-FPS，增加的采样率
  IA_FPS: False         # 是否使用IA-FPS

  test_area: 5
  fea_dim: 6              # feature dimension
  use_xyz: True

  # global_feat: 'eXYrgb'
  # ver_value: 'ptn'
  # learned_embeddings: True
  pc_augm_rot: 1
  pc_augm_jitter: 1

  use_softmax: True
  use_norm: False

  use_rgb: True           # whether to use RGB information, SemanticKITTI has no RGB, but remission
  nsample: 30             # knn 

  near_clusters2point: 6
  near_points2cluster: 50

  k_nn_adj: 5
  k_nn_local: 20
  BR_tolerance: 1

  # -------------network setting---------------------
  arch: 'superpoint_fcn_net' # network architecture
  # arch: 'superpoint_net' # network architecture
  # arch: 'PSPT' # network architecture

  dropout: 0.3

  batch_size: 32
  batch_size_val: 24
  batch_size_test: 1
  ignore_label: -100

  epochs: 2000
  start_epoch: 0

  workers: 4
  save_freq: 1            # save frequence
  print_freq: 1           # print frequence
  eval_freq: 1

  base_lr: 0.001          # sgd base_lr
  momentum: 0.9           # momentum
  weight_decay: 0.01    # weight_decay
  use_amp: False

  re_xyz_loss: 'mse'
  re_label_loss: 'cel'
  re_sp_loss: 'cel'
  use_semantic_loss: 0    # 0: not use 1: seg 2: seal

  w_re_xyz_loss: 0.001
  w_re_label_loss: 1.0
  w_re_sp_loss: 1.0
  # w_semantic_loss: 0.0
  w_re_param_loss: 0.0
  w_re_normal_loss: 0.0
  w_normal_consistency_loss: 0.0
  w_contrastive_loss: 0.5
  w_type_loss: 0.0  # 语义类型损失权重，用于IA-FPS

  scheduler_update: epoch
  scheduler: MultiStep
  optimizer: AdamW             # optimizer: sgd or adam
  # gamma: 0.5
  # T_max: 10

  step_epoch: 25          # decay learning rate per/epoch

  multiplier: 0.1         # multiplier

  spg_out: False

  # ------------------evaluation----------------------------
  evaluate: False           # evaluate
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  visual_root: 
  visual: False

  # ------------------Distributed----------------------------
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

