DATA:
  data_name: abc
  data_root: /data/fz20/dataset/ABC # Fill in the pre-processed data path (which contains the .npy files)
  test_area: 5
  classes: 10
  fea_dim: 6
  voxel_size: 0.005
  voxel_max: 80000
  train_loop: 4
  val_loop: 0.02

TRAIN:
  #arch
  arch: boundarypointtransformer_Unit_seg_repro
  stem_transformer: True
  use_xyz: True
  sync_bn: True  # adopt sync_bn or not
  rel_query: True
  rel_key: True
  rel_value: True
  quant_size: 0.01
  downsample_scale: 8
  num_layers: 4 
  patch_size: 1 
  window_size: 1
  depths: [2, 2, 6, 2] 
  channels: [48, 96, 192, 384] 
  num_heads: [3, 6, 12, 24] 
  up_k: 3
  drop_path_rate: 0.3
  concat_xyz: True
  grid_size: 0.01
  max_batch_points: 1000000
  max_num_neighbors: 34 # For KPConv
  ratio: 0.25
  k: 16
  bandwidth: 1.3

  # training
  aug: True
  transformer_lr_scale: 0.1
  jitter_sigma: 0.005
  jitter_clip: 0.02
  scheduler_update: epoch 
  scheduler: MultiStep 
  warmup: linear
  warmup_iters: 1500
  warmup_ratio: 0.000001
  use_amp: True
  optimizer: AdamW 
  ignore_label: -100
  train_gpu: [5]
  workers: 16  # data loader workers
  batch_size: 32  # batch size for training
  batch_size_val: 6  # batch size for validation during training, memory and speed tradeoff
  base_lr: 0.001
  epochs: 200
  start_epoch: 0
  step_epoch: 30
  multiplier: 0.1
  momentum: 0.9
  weight_decay: 0.01
  drop_rate: 0.5
  manual_seed: 123
  print_freq: 1
  save_freq: 1
  save_path: runs/abc
  weight:  # path to initial weight (default: none)
  resume:  # path to latest checkpoint (default: none)
  evaluate: True  # evaluate on validation set, extra gpu memory needed and small batch_size_val is recommend
  eval_freq: 1
Distributed:
  dist_url: tcp://127.0.0.1:6789
  dist_backend: 'nccl'
  multiprocessing_distributed: True
  world_size: 1
  rank: 0

TEST:
  test_list: dataset/s3dis/list/val5.txt
  test_list_full: dataset/s3dis/list/val5_full.txt
  split: val  # split in [train, val and test]
  test_gpu: [1]
  test_workers: 4
  batch_size_test: 6
  model_path: /home/fz20/project/point-transformer-boundary/exp/abc/runs-unet-base/model/model_best.pth # Fill the path of the trained .pth file model
  save_folder: exp/abc/test # Fill the path to store the .npy files for each scene
  names_path: data/s3dis/s3dis_names.txt
  visual: True
